### ISSUE TITLE
Text on dark background should be white

### ISSUE THREAD

**Issue by 0ffTopic** [m4heshd/whatsapp-desktop-dark#151]
When typing in a dark theme, text stays gray and not white, makes it harder to read.
![image](https://user-images.githubusercontent.com/9589169/75441788-2d486480-5956-11ea-9f41-0848fd122748.png)

**Comment by raphaelluethy** [comment]
I wrote a small edit note in #152 
but as i mentioned above, add 
```css
._3u328 {
    color: var(--lighter) !important;
}
```
to styles/dark.css
