### ISSUE TITLE
Reply "Quotes" on MacOS are white + fix

### ISSUE THREAD

**Issue by raphaelluethy** [m4heshd/whatsapp-desktop-dark#152]
On macOS, if you reply to an answer, the "quoted" Msg will have a white background.

Adding 
```css
._3LVMN {
    background-color: var(--dark) !important;
    color: var(--light) !important;
}
```
to the styles/dark.css file fixed the problem for me :)

PS: Love your mod!

Cheers

Edit: I also found a "bug" where the typed text in the chatbox was grey, adding
```css
._3u328 {
    color: var(--lighter) !important;
}
```

fixed it too
